# Generated by Django 4.1.4 on 2022-12-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
